### ISSUE TITLE
Enhance the PDF Page Deleter GUI

### ISSUE THREAD

**Issue by jeturgavli** [jeturgavli/PDF_PAGE_DELETER#1]
## Hi everyone, 👋

I've developed a simple PDF Page Deleter using Tkinter that efficiently deletes specified pages from PDF files. While functional, I believe the application could greatly benefit from improvements to its design and user interface. I'm inviting contributors who are passionate about UI/UX to help enhance the GUI for a better user experience. 

**Thank You**

**Comment by Bashamega** [comment]
Hello:)
I would love to work on this issue.
It should take a lot of time from me. It should be less than a week or maybe a day.
If i am going to working on this issue, i would like you to see what i am going to be using [Custom Tkinter](https://customtkinter.tomschimansky.com/). With i should give you tkinter app a better looks.
