### ISSUE TITLE
Update the img in the readme

### ISSUE THREAD

**Issue by Bashamega** [jeturgavli/PDF_PAGE_DELETER#3]
Hello:)

I have forgot to update the omage in the read me.
I can do it

**Comment by jeturgavli** [comment]
@Bashamega 
Don't worry 
I will edit the README file later. 
Thanks for your work

**Comment by Bashamega** [comment]
> @Bashamega 
> Don't worry 
> I will edit the README file later. 
> Thanks for your work

Your welcome
